/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.larrunet.gui;

import com.larrunet.bean.Servicio;
import com.larrunet.gui.panel.PnlRegistroPagos;
import javax.swing.JDialog;
import javax.swing.JInternalFrame;

/**
 *
 * @author kael
 */
public class DialogRegistrarPago extends javax.swing.JDialog {

    PnlRegistroPagos pnlRegistroPagos;
    /**
     * Creates new form DialogRegistrarPago
     */
    public DialogRegistrarPago(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        pnlRegistroPagos = new PnlRegistroPagos();
        this.setContentPane(pnlRegistroPagos);
    }

    public DialogRegistrarPago(java.awt.Frame parent, boolean modal, Servicio servicio) {
        super(parent, modal);
        initComponents();
        pnlRegistroPagos = new PnlRegistroPagos();
        pnlRegistroPagos.mostrarServicio(servicio);
        this.setContentPane(pnlRegistroPagos);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de pagos");
        setPreferredSize(new java.awt.Dimension(747, 540));
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 747, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 537, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
